// Top-level configuration.
apply plugin: 'idea'

idea.module {
    excludeDirs += file('out')
    resourceDirs += file('template')
}

buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.7.3'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

ext {
    moduleId = 'font-loader'
    moduleName = 'Font Loader'
    moduleDescription = 'Preload systemless static and variable fonts on Android 12-17 (experimental on Android 17).'
    moduleAuthor = 'JingMatrix, Rikka; modernized by Axymorrsen'
    moduleVersionName = '1.2.0-beta2'
    moduleVersionCode = 5
}
