cmake_minimum_required(VERSION 3.19.0)
project(fontloader)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fno-exceptions -fno-rtti -ffixed-x18 -O2 -fvisibility=hidden")
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_SHARED_LINKER_FLAGS} -Wl,--hash-style=both -Wl,--gc-sections")
find_package(cxx REQUIRED CONFIG)
add_library(fontloader SHARED main.cpp)
target_link_libraries(fontloader log cxx::cxx)
